// <auto-generated />
using BagoLootAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BagoLootAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BagoLootAPI.Models.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Delivered");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ChildId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("BagoLootAPI.Models.FavoriteReindeer", b =>
                {
                    b.Property<int>("FavoriteReindeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChildId");

                    b.Property<int>("ReindeerId");

                    b.HasKey("FavoriteReindeerId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ReindeerId");

                    b.ToTable("FavoriteReindeer");
                });

            modelBuilder.Entity("BagoLootAPI.Models.Reindeer", b =>
                {
                    b.Property<int>("ReindeerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ReindeerId");

                    b.ToTable("Reindeer");
                });

            modelBuilder.Entity("BagoLootAPI.Models.Toy", b =>
                {
                    b.Property<int>("ToyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChildId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ToyId");

                    b.HasIndex("ChildId");

                    b.ToTable("Toy");
                });

            modelBuilder.Entity("BagoLootAPI.Models.FavoriteReindeer", b =>
                {
                    b.HasOne("BagoLootAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BagoLootAPI.Models.Reindeer", "Reindeer")
                        .WithMany("Fans")
                        .HasForeignKey("ReindeerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BagoLootAPI.Models.Toy", b =>
                {
                    b.HasOne("BagoLootAPI.Models.Child", "Child")
                        .WithMany("Toys")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
